from copy import deepcopy

from globus_sdk.testing.models import RegisteredResponse, ResponseSet

from ._common import (
    GROUP,
    TWO_HOP_TRANSFER_FLOW_DOC,
    TWO_HOP_TRANSFER_FLOW_ID,
    TWO_HOP_TRANSFER_RUN,
    TWO_HOP_TRANSFER_RUN_ID,
    USER1,
    USER2,
)

WEB_INPUT_ID = "e35d1f92-3e2a-4c1c-8f36-7ce4f00f9d2c"
AUTHENTICATION_POLICY_ID = "6f2c1d7e-3b4a-4a5e-9f0f-8f2a1b7c4d9e"

OPTION_ID_APPROVE = "8f14e45f-ceea-467e-add1-6a6b672efe31"
OPTION_ID_REJECT = "c9f0f895-fb98-4a4b-b845-4ded0c6b6d3c"

# Mirrors the JSON Schema shape generated by
# globus_flows.engines.execution.lifecycle.web_inputs.schemas.generate_schema_from_options
WEB_INPUT_INPUT_SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "Please select an option",
    "type": "string",
    "oneOf": [
        {
            "const": OPTION_ID_APPROVE,
            "title": "Approve",
            "description": "Proceed with the production deployment.",
        },
        {
            "const": OPTION_ID_REJECT,
            "title": "Reject",
            "description": "Halt the deployment.",
        },
    ],
}

WEB_INPUT_DOC = {
    "id": WEB_INPUT_ID,
    "status": "open",
    "user_roles": ["viewer", "respondent"],
    "input_type": "selection",
    "input_schema": WEB_INPUT_INPUT_SCHEMA,
    "context": {
        "title": "Approve deployment to production?",
        "presentation_style": "text",
        "text": "The nightly build has passed all tests and is ready to deploy.",
    },
    "options": [
        {
            "option_id": OPTION_ID_APPROVE,
            "label": "Approve",
            "description": "Proceed with the production deployment.",
        },
        {
            "option_id": OPTION_ID_REJECT,
            "label": "Reject",
            "description": "Halt the deployment.",
        },
    ],
    "roles": {
        "viewer_urns": [GROUP],
        "respondent_urns": [USER2],
    },
    "creator_urn": USER1,
    "flow": {
        "id": TWO_HOP_TRANSFER_FLOW_ID,
        "title": TWO_HOP_TRANSFER_FLOW_DOC["title"],
    },
    "run": {
        "id": TWO_HOP_TRANSFER_RUN_ID,
        "label": TWO_HOP_TRANSFER_RUN["label"],
    },
    "created_timestamp": "2026-08-01T10:30:00+00:00",
    "edited_timestamp": "2026-08-01T10:30:00+00:00",
    "closed_timestamp": None,
}

WEB_INPUT_DOC_CLOSED = deepcopy(WEB_INPUT_DOC)
WEB_INPUT_DOC_CLOSED["status"] = "closed"
WEB_INPUT_DOC_CLOSED["closed_timestamp"] = "2026-08-02T09:12:00+00:00"

# `WEB_INPUT_DOC`'s context is "text" presentation style; this variant covers
# "table" presentation style.
WEB_INPUT_DOC_TABLE_CONTEXT = deepcopy(WEB_INPUT_DOC)
WEB_INPUT_DOC_TABLE_CONTEXT["context"] = {
    "title": "Approve deployment to production?",
    "presentation_style": "table",
    "rows": [
        {"field": "Environment", "value": "production"},
        {"field": "Version", "value": "v2.4.1"},
        {"field": "Requested By", "value": "pete@kreb.star"},
    ],
}

NOT_FOUND_RESPONSE = {
    "error": {
        "code": "NOT_FOUND",
        "detail": f"No Web Input exists with id value {WEB_INPUT_ID}",
    }
}

# Raised by `authorize_get_web_input` when the caller has a role on the web input
# but the associated flow's authentication policy is not satisfied by their session.
WEB_INPUT_SUMMARY_FOR_GARE = {
    "id": WEB_INPUT_ID,
    "status": "open",
    "user_roles": ["respondent"],
    "input_type": "selection",
    "title": "Approve deployment to production?",
    "flow": {
        "id": TWO_HOP_TRANSFER_FLOW_ID,
        "title": TWO_HOP_TRANSFER_FLOW_DOC["title"],
    },
    "run": {
        "id": TWO_HOP_TRANSFER_RUN_ID,
        "label": TWO_HOP_TRANSFER_RUN["label"],
    },
    "created_timestamp": "2026-08-01T10:30:00+00:00",
    "edited_timestamp": "2026-08-01T10:30:00+00:00",
    "closed_timestamp": None,
}
AUTH_POLICY_REQUIRED_RESPONSE = {
    "web_input_summary": WEB_INPUT_SUMMARY_FOR_GARE,
    "error": {
        "code": "AUTHENTICATION_POLICY_REQUIRED",
        "detail": (
            "None of the identities in session meet the requirements "
            "for the authentication policy associated with this Web Input's flow. "
            "Reauthenticate as an identity that has permission "
            "to view the Web Input "
            "and can meet the requirements for the attached authentication policy."
        ),
    },
    "code": "AuthenticationPolicyRequired",
    "authorization_parameters": {
        "session_required_policies": [AUTHENTICATION_POLICY_ID],
        "session_message": (
            "Globus Flows detected an unsatisfied session policy for this web input."
        ),
    },
}

RESPONSES = ResponseSet(
    metadata={
        "web_input_id": WEB_INPUT_ID,
        "flow_id": TWO_HOP_TRANSFER_FLOW_ID,
        "run_id": TWO_HOP_TRANSFER_RUN_ID,
    },
    default=RegisteredResponse(
        service="flows",
        path=f"/web_inputs/{WEB_INPUT_ID}",
        json=WEB_INPUT_DOC,
    ),
    closed=RegisteredResponse(
        service="flows",
        path=f"/web_inputs/{WEB_INPUT_ID}",
        json=WEB_INPUT_DOC_CLOSED,
    ),
    table_context=RegisteredResponse(
        service="flows",
        path=f"/web_inputs/{WEB_INPUT_ID}",
        json=WEB_INPUT_DOC_TABLE_CONTEXT,
    ),
    not_found=RegisteredResponse(
        service="flows",
        path=f"/web_inputs/{WEB_INPUT_ID}",
        status=404,
        json=NOT_FOUND_RESPONSE,
    ),
    auth_policy_required=RegisteredResponse(
        service="flows",
        path=f"/web_inputs/{WEB_INPUT_ID}",
        status=403,
        json=AUTH_POLICY_REQUIRED_RESPONSE,
    ),
)
