#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import globus_sdk

# sphinx extensions (minimally, we want autodoc and viewcode to build the site)
extensions = ["sphinx.ext.autodoc", "sphinx.ext.todo", "sphinx.ext.viewcode"]

# The master toctree document.
master_doc = "index"

project = "globus-sdk-python"
copyright = "2016, Globus"
author = "Globus Team"
# The short X.Y version.
version = globus_sdk.__version__
# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["_build"]

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# HTML Theme Options
html_show_sourcelink = True
html_sidebars = {
    "**": ["logo-text.html", "globaltoc.html", "localtoc.html", "searchbox.html"]
}
html_theme = "sphinx_material"
html_theme_options = {
    "nav_title": "Globus SDK",
    # Set the color and the accent color
    "color_primary": "#27518F",
    "color_accent": "light-blue",
    # Set the repo location to get a badge with stats
    "repo_url": "https://github.com/globus/globus-sdk-python/",
    "repo_name": "Globus SDK",
    # Visible levels of the global TOC; -1 means unlimited
    "globaltoc_depth": 2,
    # If False, expand all TOC entries
    "globaltoc_collapse": False,
}

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "friendly"

# Output file base name for HTML help builder.
htmlhelp_basename = "globus-sdk-pythondoc"
