[mypy]
# baseline at --strict, but then allow exemptions
strict = true
sqlite_cache = true
warn_unreachable = true
warn_no_return = true
allow_untyped_calls = true
allow_untyped_defs = true
explicit_package_bases = true

[mypy-docs.examples.token_storage.dynamodb_token_storage]
# example needs to be allowed to import boto3
ignore_missing_imports = true
disable_error_code = import-not-found
