name: update-pr-references
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  update_pr_numbers_in_change_fragments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: true
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.x'
      - name: update any PR numbers in change fragments
        run: |
          python ./changelog.d/update-pr-refs.py
          if [ "$(git status --porcelain)" = "" ]; then
            echo "no changes"
          else
            git add changelog.d/
            git \
              -c user.name="GitHub Actions" \
              -c user.email="actions@github.com" \
              commit -m '(actions) update PR references'
            git push origin
          fi
